name: codio-publish
on:
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@master
        with:
          client-id: ${{ secrets.CODIO_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_SECRET_ID }}
          dir: ./
          course-name: Demo GitHub API for Emeritus 
          changelog: ${{ github.event.head_commit.message }}
          yml: ./.github/yaml_map